### ISSUE TITLE
Cannot log in with GitHub

### ISSUE THREAD

**Issue by aft3rlife** [btk/memo#13]
Using version 1.0.3, when trying to log in with GitHub on Mac OS 10.13.6, I get this error:

`Refused to display 'https://github.com/login?client_id=redacted&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3Dredacted%26redirect_uri%3Dhttps%253A%252F%252Fapi.usememo.com%252Fgithub%252F%26refresh%3Dtrue%26scope%3Dgist' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
index.js:47 DOMException: Blocked a frame with origin "https://app.usememo.com" from accessing a cross-origin frame.
    at t.value (https://app.usememo.com/static/js/main.24baf891.chunk.js:1:77766)
    at onLoad (https://app.usememo.com/static/js/main.24baf891.chunk.js:1:78519)
    at Object.<anonymous> (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:133428)
    at d (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:133466)
    at https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:134104
    at E (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:134193)
    at S (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:134629)
    at x (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:134441)
    at P (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:135529)
    at qr (https://app.usememo.com/static/js/2.951b4b11.chunk.js:1:162952)`

This is the latest version downloaded from the website.

**Comment by btk** [comment]
Hey, this was an issue caused by the latest version of Chrome no allowing iframe for github, I have fixed this few weeks ago.
